#!/usr/bin/env bash
# displays numbers from 1 to 100 print FizzBuzz if mult of 3 and 5 Fizz if mult by 3 Buzz if mult by 5 Otherwise, displays the number

i=1

while [ $i -lt 101 ]
do
	if [ $((i%15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i%3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
