#!/usr/bin/env bash
# displays bad luck 4th good luck on 8th and Best School for the other iterations

i=1

while [ $i -lt 11 ]
do
	if [ "$i" == 4 ]
	then
		echo "bad luck"
	elif [ "$i" == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
