#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
HOUR=0
while [ $HOUR -lt 13 ]
do
	echo "Hour: $HOUR"
	MINT=1
	while [ $MINT -lt 60 ]
	do
		echo "$MINT"
		((MINT++))
	done
	((HOUR++))
done
