#!/usr/bin/env bash
# change facebook and localhost address

# Check if the script is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Backup the original /etc/hosts file
cp /etc/hosts ~/hosts.new

# Add the custom hostnames and IPs
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
